# Generated by Django 5.2.8 on 2025-11-24 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリー名')),
            ],
        ),
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('study_time', models.IntegerField(verbose_name='学習時間(分)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='学習日')),
                ('memo', models.TextField(blank=True, verbose_name='詳細メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.category', verbose_name='カテゴリー')),
            ],
        ),
    ]
